global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'test-api-gateway'
    static_configs:
      - targets: ['test-api-gateway:8080']

  - job_name: 'test-collector'
    static_configs:
      - targets: ['test-collector:8081']

  - job_name: 'test-stream-processor'
    static_configs:
      - targets: ['test-stream-processor:8082']

  - job_name: 'test-ml-engine'
    static_configs:
      - targets: ['test-ml-engine:8083']

  - job_name: 'test-operator'
    static_configs:
      - targets: ['test-operator:8084'] 