environment: development
version: "0.1.0"

# サーバー設定
port: 8080

# データベース設定
database:
  host: "localhost"
  port: 5432
  user: "streamforge"
  password: "streamforge"
  name: "streamforge"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: "5m"

# Redis設定
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5

# Jaeger設定
jaeger_endpoint: "http://localhost:14268/api/traces"

# レート制限設定
rate_limit:
  enabled: true
  requests_per_minute: 1000
  burst_size: 100

# セキュリティ設定
security:
  jwt_secret: "your-secret-key-change-in-production"
  jwt_expiration: "24h"
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  cors_allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  cors_allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"

# ログ設定
logging:
  level: "info"
  format: "json"
  output: "stdout"
  include_caller: true
  include_stacktrace: false 