global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # StreamForge API Gateway
  - job_name: 'streamforge-api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # StreamForge Stream Processor
  - job_name: 'streamforge-stream-processor'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # StreamForge Dashboard
  - job_name: 'streamforge-dashboard'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Node Exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

  # PostgreSQL (if pg_exporter is running)
  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']

  # Redis (if redis_exporter is running)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121'] 